### ISSUE TITLE
Pressing Calculate Result multiple times crashes the app

### ISSUE THREAD

**Issue by WillDaru22** [cjwilson2020/WDYWW#17]
Using a Google Pixel 3a, after selecting all of the default options in the theatre and then pressing calculate result multiple times in a row, the app crashes, restarts, then crashes again and shuts down.  I was able to get an initial recommendation after the first crash and reset but pressing the button further crashed the app completely.

Severity:  Critical
Users may end up pressing the button multiple times either on accident or on purpose and having the app crash every time this happens would not be ideal.

Suggestions:  Potentially have the button disappear until the app finishes calculating the results before appearing again when the button is ready to be pushed again.  Make sure arrays are of proper length and that if the user does not select any options they are either prompted to or the app allows them to not select any options.

Error that was sent upon shutdown:
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.whatdoyouwannawatch, PID: 15074
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
        at java.util.ArrayList.get(ArrayList.java:439)
        at com.example.whatdoyouwannawatch.BackStage.calcResult(BackStage.java:130)
        at com.example.whatdoyouwannawatch.ResultActivity$3.onCallback(ResultActivity.java:126)
        at com.example.whatdoyouwannawatch.MainActivity$5.onDataChange(MainActivity.java:170)
        at com.google.firebase.database.Query$1.onDataChange(Query.java:179)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:75)
        at com.google.firebase.database.core.view.DataEvent.fire(DataEvent.java:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(EventRaiser.java:55)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process: Sending signal. PID: 15074 SIG: 9

**Comment by yuanchenGH** [comment]
Resolved.  It's caused by the big history file which is pushed to firebase without enough space to store it.
