### ISSUE TITLE
Can't change streaming services

### ISSUE THREAD

**Issue by bkinder2385** [cjwilson2020/WDYWW#8]
The app crashes when I'm logged in and try to change my streaming services in my profile.

**Comment by bkinder2385** [comment]
Using a Moto Z Play Android version 8.0.0

**Comment by WillDaru22** [comment]
Tested this with a google pixel 3a as well.  App immediately crashes upon trying to press the streaming services button.

Severity: Critical

Error Given:
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.whatdoyouwannawatch, PID: 17304
    java.lang.IllegalStateException: Could not find method onClickServiceSettings(View) in a parent or ancestor Context for android:onClick attribute defined on view class androidx.appcompat.widget.AppCompatButton with id 'button8'
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.resolveMethod(AppCompatViewInflater.java:447)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:405)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
